### ISSUE TITLE
Running tests from command line just hangs when selenium launches browser

### ISSUE THREAD

**Issue by lkiss80** [safarijv/django-qunit-ci#3]
I'm able to run some simple qunit tests in the browser.  However, when I run with the django test command, selenium launches a chrome window, and it just hangs.  When I CTRL-C out of the tests, I see the error: URLError: <urlopen error [Errno 61] Connection refused>.

test command:
python manage.py test --with-django-qunit app_name.tests.qunit.test_case
hangs on URL:
http://app_name.local:8081/qunit/test/?class=app_name.tests.qunit.test_case.QUnitIntroTestCase

I run other selenium tests and they work great.

Any ideas?

**Comment by jmbowman** [comment]
Closing this as unverifiable, let me know if anybody is still having trouble with this.
